### ISSUE TITLE
unable to bootstrap carthage

### ISSUE THREAD

**Issue by ninokierulf** [Swinject/SwinjectMVVMExample#1] opened 2015-09-21 08:17 UTC
```
*** Building scheme "Result-watchOS" in Result.xcodeproj
xcodebuild: error: Failed to build project Result with scheme Result-watchOS.
    Reason: The run destination My Mac is not valid for Running the scheme 'Result-watchOS'.
A shell task failed with exit code 70:
xcodebuild: error: Failed to build project Result with scheme Result-watchOS.
    Reason: The run destination My Mac is not valid for Running the scheme 'Result-watchOS'
```

**Comment by yoichitgy** [comment] 2015-09-21 11:22
If you see the error, run `carthage bootstrap --no-build` then `carthage build`. If the latter command fails, run `carthage build` again. After running it a few times, the build passes (at least in my environment).

I don't know the cause of the problem. It might be Carthage or the specific version of ReactiveCocoa. I'll update the `Cartfile` later when all the frameworks are updated to support Swift 2. Then with the new `Cartfile`, the problem might be fixed.

**Comment by yoichitgy** [comment] 2015-12-11 08:11
I don't see the issue with the latest Carthage (0.11), so am going to close it.

**Closed as completed by yoichitgy** 2015-12-11 08:11 UTC
Labels: question

**Comment by joelorenz** [comment] 2016-04-13 09:50
Hi, 
I'm having some issue when trying to bootstrap carthage and resulted to this error

**Command line error:**
*\* BUILD FAILED **
The following build commands failed:
    CompileSwift normal arm64 /Users/Documents/SwinjectMVVMExample/Carthage/Checkouts/Nimble/Nimble/Adapters/NimbleXCTestHandler.swift
    CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
(2 failures)

**XCode Error**:
< No such module 'ReactiveCocoa' >
